var JSON;if(!JSON){JSON={}}(function(){function f(n){return n<10?"0"+n:n}if(typeof Date.prototype.toJSON!=="function"){Date.prototype.toJSON=function(key){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+f(this.getUTCMonth()+1)+"-"+f(this.getUTCDate())+"T"+f(this.getUTCHours())+":"+f(this.getUTCMinutes())+":"+f(this.getUTCSeconds())+"Z":null
};String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(key){return this.valueOf()}}var cx=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,escapable=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,gap,indent,meta={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},rep;
function quote(string){escapable.lastIndex=0;return escapable.test(string)?'"'+string.replace(escapable,function(a){var c=meta[a];return typeof c==="string"?c:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)
})+'"':'"'+string+'"'}function str(key,holder){var i,k,v,length,mind=gap,partial,value=holder[key];if(value&&typeof value==="object"&&typeof value.toJSON==="function"){value=value.toJSON(key)}if(typeof rep==="function"){value=rep.call(holder,key,value)
}switch(typeof value){case"string":return quote(value);case"number":return isFinite(value)?String(value):"null";case"boolean":case"null":return String(value);case"object":if(!value){return"null"}gap+=indent;
partial=[];if(Object.prototype.toString.apply(value)==="[object Array]"){length=value.length;for(i=0;i<length;i+=1){partial[i]=str(i,value)||"null"}v=partial.length===0?"[]":gap?"[\n"+gap+partial.join(",\n"+gap)+"\n"+mind+"]":"["+partial.join(",")+"]";
gap=mind;return v}if(rep&&typeof rep==="object"){length=rep.length;for(i=0;i<length;i+=1){if(typeof rep[i]==="string"){k=rep[i];v=str(k,value);if(v){partial.push(quote(k)+(gap?": ":":")+v)}}}}else{for(k in value){if(Object.prototype.hasOwnProperty.call(value,k)){v=str(k,value);
if(v){partial.push(quote(k)+(gap?": ":":")+v)}}}}v=partial.length===0?"{}":gap?"{\n"+gap+partial.join(",\n"+gap)+"\n"+mind+"}":"{"+partial.join(",")+"}";gap=mind;return v}}if(typeof JSON.stringify!=="function"){JSON.stringify=function(value,replacer,space){var i;
gap="";indent="";if(typeof space==="number"){for(i=0;i<space;i+=1){indent+=" "}}else{if(typeof space==="string"){indent=space}}rep=replacer;if(replacer&&typeof replacer!=="function"&&(typeof replacer!=="object"||typeof replacer.length!=="number")){throw new Error("JSON.stringify")
}return str("",{"":value})}}if(typeof JSON.parse!=="function"){JSON.parse=function(text,reviver){var j;function walk(holder,key){var k,v,value=holder[key];if(value&&typeof value==="object"){for(k in value){if(Object.prototype.hasOwnProperty.call(value,k)){v=walk(value,k);
if(v!==undefined){value[k]=v}else{delete value[k]}}}}return reviver.call(holder,key,value)}text=String(text);cx.lastIndex=0;if(cx.test(text)){text=text.replace(cx,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)
})}if(/^[\],:{}\s]*$/.test(text.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))){j=eval("("+text+")");
return typeof reviver==="function"?walk({"":j},""):j}throw new SyntaxError("JSON.parse")}}}());if(typeof Array.isArray==="undefined"){Array.isArray=function(a){return Object.prototype.toString.call(a)==="[object Array]"
}}if(typeof Array.indexOf==="undefined"){Array.prototype.indexOf=function(c,d){for(var b=(d||0),a=this.length;b<a;b++){if(this[b]===c){return b}}return -1}}"use strict";window.NOKIA=window.NOKIA||{};window.NOKIA.sso=window.NOKIA.sso||{};
"use strict";if(!window.NOKIA.sso.Logging){window.NOKIA.sso.Logging=(function(){var a=false;var b;return{log:function(){var f,c,d;if(a){if(window.console&&window.console.log){if(arguments.length===1){window.console.log(arguments[0])
}else{if(arguments.length===2){window.console.log(arguments[0],arguments[1])}else{if(arguments.length===3){window.console.log(arguments[0],arguments[1],arguments[2])}else{window.console.log(arguments)}}}}if(b){f=window.document.getElementById(b);
if(f){for(c=0;c<arguments.length;c++){d=document.createTextNode(""+arguments[c]+" ");f.appendChild(d)}d=document.createElement("br");f.appendChild(d)}}}},error:function(g){var f,c,d;if(a){if(window.console&&window.console.trace){window.console.trace()
}if(b){f=window.document.getElementById(b);if(f){d=document.createTextNode("ERROR: "+g+"");f.appendChild(d);d=document.createElement("br");f.appendChild(d)}}}throw new Error(g)},setLogElement:function(c){b=c
},setEnabled:function(c){a=c}}}())}"use strict";window.NOKIA.sso.Util=(function(){var a=1;return{generateUniqueID:function(){var b=Math.random()*100000000;b=Math.floor(b);b=b*20;b+=a;a++;return b},getQueryParameter:function(d){var c="[?&]"+d+"=([^&#]*)";
var e=new RegExp(c);var b=e.exec(window.location.href);if(b===null){return undefined}else{return decodeURIComponent(b[1])}}}}());"use strict";if(!window.NOKIA.sso.Communication){window.NOKIA.sso.Communication=(function(){var g=["https://account.nokia.com"];
var b=window.NOKIA.sso.Logging.log;var f=window.NOKIA.sso.Logging.error;var a="NoA SDK: ";var i=false;var e;var d=[];var c="NOKIA.sso.Communication:";if(!window.postMessage){i=true}function h(){var j=function(n){b(a+"Received external message: ",n);
var m=false;for(var k=0;k<g.length;k++){if(n.origin===g[k]){m=true;break}}if(m){if(n.data.indexOf(c)===0){var l=n.data.substr(c.length);window.NOKIA.sso.Communication.sendMessageToLocal(l)}else{b(a+"Message did not have correct prefix, ignoring message.")
}}else{b(a+"Message origin not allowed, ignoring message. origin="+n.origin)}};if(window.addEventListener){window.addEventListener("message",j,false)}else{if(window.attachEvent){window.attachEvent("onmessage",j)
}else{f(a+"Browser supports postMessage but no way found to attach to the event")}}}return{addMessageListener:function(j){if(typeof j!=="function"){f(a+"addMessageListener(): Argument must be a function")
}if(d.length===0&&!i){h()}d.push(j)},sendMessageToLocal:function(k){if(typeof k!=="string"){f(a+"sendMessageToLocal(): Argument must be a string")}b(a+"Sending message to "+d.length+" local callbacks");
for(var j=0;j<d.length;j++){d[j](k)}},sendMessageToParent:function(n){var l=window.parent;if(!l||l===window){f(a+"sendMessageToParent(): No parent frame available")}if(typeof n!=="string"){f(a+"sendMessageToParent(): Argument must be a string")
}var j=false;try{if(l.NOKIA&&l.NOKIA.sso&&l.NOKIA.sso.Communication){j=true}}catch(o){}if(j){b(a+"Sending message using same-domain communication");l.NOKIA.sso.Communication.sendMessageToLocal(n)}else{if(!i){if(!e){f(a+"sendMessageToParent(): Callback URL has not been set")
}b(a+"Sending message using postMessage");l.postMessage(c+n,e)}else{if(!e){f(a+"sendMessageToParent(): Callback URL has not been set")}b(a+"Sending message using callback URL");var k=e+"#msg:"+encodeURIComponent(n);
var p=document.createElement("iframe");p.setAttribute("id","noa_communication_frame_"+window.NOKIA.sso.Util.generateUniqueID());p.setAttribute("src",k);p.style.display="none";p.style.width="1px";p.style.height="1px";
var m=document.getElementById("noasdk_iframe_container");if(!m){f(a+"sendMessageToParent(): noasdk_iframe_container element not found")}m.appendChild(p)}}},setCallbackUrl:function(j){if(!/^https?:\/\/[a-z0-9\-]+(\.[a-z0-9\-]+)*(:[0-9]+)?(\/.*)?$/i.test(j)){f(a+"setCallbackUrl(): Invalid format for callback URL.  url="+j)
}b(a+"Setting callback URL to: "+j);e=j},getCallbackUrl:function(){return e},addAllowedHost:function(j){if(!/^https?:\/\/[a-z0-9\-]+(\.[a-z0-9\-]+)*(:[0-9]+)?$/i.test(j)){f(a+"addAllowedHost(): Invalid format for host")
}j=j.toLowerCase();b(a+"Adding allowed message source host:",j);g.push(j)}}}())}"use strict";if(!window.NOKIA.sso.SDK){(function(){var b=window.NOKIA.sso.Logging.log;var a=window.NOKIA.sso.Logging.error;
var c=window.NOKIA.sso.Util.getQueryParameter;window.NOKIA.sso.SDK=function(){var o={};var g="https://account.nokia.com";var w="jsSdk=1";var m=window.NOKIA.sso.Util.generateUniqueID();var k=false;var p="NoA SDK ("+m+"): ";
var B={authentication:[],sessionAuthentication:[],registration:[],failure:[],close:[],passwordRecovery:[],newFrame:[],resizeFrame:[]};var f;var h;var r;var e;var s;var u;var z;function j(){if(!k){a(p+"SSO object has not been initialized properly")
}}function t(D){if(!D||!D.event||B[D.event]===undefined){a(p+"invalid event type")}if(typeof(D.closeFrame)!=="boolean"){a(p+"closeFrame property missing")}if(typeof(D.jsSdkId)!=="number"){a(p+"jsSdkId property missing")
}if(D.event==="newFrame"||D.event==="resizeFrame"){if(D.event==="newFrame"&&typeof(D.url)!=="string"){a(p+"url property missing")}if(typeof(D.width)!=="number"){a(p+"width property missing")}if(typeof(D.height)!=="number"){a(p+"height property missing")
}if(typeof(D.page)!=="string"){a(p+"page property missing")}}else{if(D.event==="failure"){if(typeof(D.reason)!=="string"){a(p+"reason property missing")}}else{if(D.event==="close"){if(!D.closeFrame){a(p+"closeFrame not allowed")
}}}}}function y(G,F){for(var E=0;E<F.length;E++){var D=F[E];D(G,o)}}function C(E){t(E);b(p+"firing event: ",E);var D=B[E.event];y(E,D)}function A(E,I,F,D,H){var G={event:"newFrame",url:E,page:I,width:F,height:D,closeFrame:true,jsSdkId:m};
if(H){G.hidden=true}C(G)}function n(E){b(p+"received message: "+E);var D=JSON.parse(E);t(D);if(D.jsSdkId===m){C(D)}else{b(p+"jsSdkId from message does not match");if(D.event==="authentication"){C({event:"sessionAuthentication",jsSdkId:m,closeFrame:true})
}return}}function v(E,D){D=D||{};if(typeof(D.lang)==="string"&&D.lang.match(/^[a-zA-Z0-9_\-]+$/)){E=E+"&lang="+encodeURIComponent(D.lang)}if(typeof(D.country)==="string"&&D.country.match(/^[a-zA-Z]+$/)){E=E+"&country="+encodeURIComponent(D.country)
}if(typeof(D.campaignId)==="string"){E=E+"&campaignID="+encodeURIComponent(D.campaignId)}if(typeof(D.ch)==="string"){E=E+"&ch="+encodeURIComponent(D.ch)}else{E=E+"&ch="}if(typeof(D.c6)==="string"){E=E+"&c6="+encodeURIComponent(D.c6)
}else{E=E+"&c6="}if(typeof(D.c23)==="string"){E=E+"&c23="+encodeURIComponent(D.c23)}else{E=E+"&c23="}return E}function q(F){var E;var D=window.NOKIA.sso.Communication.getCallbackUrl();var G=e+"?jsSdkId="+m+"&jsCallbackUrl="+encodeURIComponent(D);
E=(g+"/restsso/joinsso?oauth_consumer_key="+encodeURIComponent(r)+"&success_url="+encodeURIComponent(G)+"&callbackUrl="+encodeURIComponent(D)+"&serviceId="+encodeURIComponent(f)+"&jsSdkId="+m+"&"+w+"&ui=frame&sized=true");
E=v(E,F);return E}function i(F){var E;var D=window.NOKIA.sso.Communication.getCallbackUrl();var G=u+"?jsSdkId="+m+"&jsCallbackUrl="+encodeURIComponent(D);E=(g+"/oauth2/authorize?client_id="+encodeURIComponent(s)+"&redirect_uri="+encodeURIComponent(G)+"&callbackUrl="+encodeURIComponent(D)+"&response_type="+encodeURIComponent(z)+"&serviceId="+encodeURIComponent(f)+"&jsSdkId="+m+"&ui=frame&sized=true");
E=v(E,F);return E}function l(E){var D=o.getSignInUrl();D+="&noSession="+encodeURIComponent(g+"/acct/public/jsNoSession");return D}function x(E){var D=o.getSignInUrl();D+="&immediate=true";D+="&jssdk_no_session=true";
return D}o.init=function(F){var E;var D;b(p+"init() called");if(F===undefined){a(p+"init(): argument is required")}if(F.serviceId){f=F.serviceId}else{a(p+"init(): serviceId parameter is mandatory")}if(F.authenticationMethod==="websso"){h="websso";
if(F.webSsoConsumerKey){r=F.webSsoConsumerKey}else{a(p+"init(): webSsoConsumerKey parameter is mandatory for Web SSO")}if(F.webSsoSuccessUrl){e=F.webSsoSuccessUrl}else{a(p+"init(): webSsoSuccessUrl parameter is mandatory for Web SSO")
}if(F.webSsoBaseUrl){E=F.webSsoBaseUrl;E=E.toLowerCase();E=E.replace("/$","");window.NOKIA.sso.Communication.addAllowedHost(E)}}else{if(F.authenticationMethod==="oauth2"){h="oauth2";if(F.oauth2ClientId){s=F.oauth2ClientId
}else{a(p+"init(): oauth2ClientId parameter is mandatory for OAuth2")}if(F.oauth2RedirectUri){u=F.oauth2RedirectUri}else{a(p+"init(): oauth2RedirectUri parameter is mandatory for OAuth2")}z="code"}else{a(p+"init(): unsupported authenticationMethod")
}}if(F.callbackUrl){window.NOKIA.sso.Communication.setCallbackUrl(F.callbackUrl)}if(F.callback){D=F.callback;if(typeof(D)==="function"){o.registerCallback("all",D)}else{if(Array.isArray(D)){for(var G=0;
G<D.length;G++){if(typeof(D[G])==="function"){o.registerCallback("all",D[G])}else{a(p+"init(): invalid argument type for callback parameter")}}}else{a(p+"init(): invalid argument type for callback parameter")
}}}window.NOKIA.sso.Communication.addMessageListener(n);k=true;b(p+"init() successful")};o.registerCallback=function(E,F){if(E==="all"){for(var D in B){if(B.hasOwnProperty(D)){B[D].push(F)}}}else{if(B[E]){B[E].push(F)
}else{a(p+"registerCallback(): unknown event type '"+E+"'")}}};o.unregisterCallback=function(F){for(var E in B){if(B.hasOwnProperty(E)){var D=B[E].indexOf(F);if(D>=0){B[E].splice(D,1)}}}};o.performSignIn=function(E){var D=560;
A(o.getSignInUrl(E),"signIn",420,D)};o.getSignInUrl=function(D){j();if(h==="websso"){return q(D)}else{if(h==="oauth2"){return i(D)}else{a("Unsupported authenticationMethod")}}};o.performPassiveAuthentication=function(D){A(o.getPassiveAuthenticationUrl(D),"authentication:passiveAuthentication",1,1,true)
};o.getPassiveAuthenticationUrl=function(D){j();if(h==="websso"){return l(D)}else{if(h==="oauth2"){return x(D)}else{a("Unsupported authenticationMethod")}}};o.performRegistration=function(E){var D=640;
A(o.getRegistrationUrl(E),"registration:email",600,D)};o.getRegistrationUrl=function(F){var E;var G=o.getSignInUrl();G=G.replace("&sized=true","");var D=window.NOKIA.sso.Communication.getCallbackUrl();
E=(g+"/acct/register?serviceId="+encodeURIComponent(f)+"&returnurl="+encodeURIComponent(G)+"&callbackUrl="+encodeURIComponent(D)+"&serviceId="+encodeURIComponent(f)+"&jsSdkId="+m+"&"+w+"&ui=frame&sized=true");
E=v(E,F);return E};o.performPasswordRecovery=function(D){A(o.getPasswordRecoveryUrl(D),"passwordRecovery:recoveryRequest",420,560)};o.getPasswordRecoveryUrl=function(F){var E;var G=o.getSignInUrl();var D=window.NOKIA.sso.Communication.getCallbackUrl();
E=(g+"/acct/passwordReminder?serviceId="+encodeURIComponent(f)+"&returnurl="+encodeURIComponent(G)+"&callbackUrl="+encodeURIComponent(D)+"&serviceId="+encodeURIComponent(f)+"&jsSdkId="+m+"&"+w+"&ui=frame&sized=true");
E=v(E,F);return E};o.sendCloseEvent=function(){var D={event:"close",jsSdkId:m,closeFrame:true};C(D)};o.log=b;o.error=a;return o};function d(f){var e=Number(c("jsSdkId"));if(isNaN(e)){a("NoA SDK: jsSdkId parameter not present or invalid")
}f.jsSdkId=e;var h=c("jsCallbackUrl");if(!e){a("NoA SDK: jsCallbackUrl parameter not present or invalid")}var g=JSON.stringify(f);if(g.length>1024){b("NOA SDK: Warning: message total size: ",g.length)}window.NOKIA.sso.Communication.setCallbackUrl(h);
window.NOKIA.sso.Communication.sendMessageToParent(g)}window.NOKIA.sso.SDK.sendAuthenticationEvent=function(e){var f;if(e){f=e.customData}d({event:"authentication",customData:f,closeFrame:true})};window.NOKIA.sso.SDK.sendAuthenticationFailureEvent=function(e){d({event:"failure",reason:"authentication:service",closeFrame:true})
}}())}"use strict";if(!window.NOKIA.sso.SDK.Default){window.NOKIA.sso.SDK.Default={};window.NOKIA.sso.SDK.Default.createFrameHandler=function(l){var e=window.NOKIA.sso.Logging.log;var k=window.NOKIA.sso.Logging.error;
var c="NoA SDK (frame handler): ";var d;var j="noasdk";var g="×";var h=true;var a;var i;var b;var f=0;if(l&&l.containerElementId){d=l.containerElementId}else{k(c+"containerElementId is mandatory property")
}if(l.prefix!==undefined){if(typeof(l.prefix)==="string"&&/^[a-zA-Z][a-zA-Z0-9_]*$/.test(l.prefix)){j=l.prefix}else{k(c+"Invalid prefix parameter")}}if(l.closeLinkText!==undefined){if(typeof(l.closeLinkText)==="string"){g=l.closeLinkText
}else{k(c+"Invalid closeLinkText parameter")}}if(l.styling!==undefined){if(typeof(l.styling)==="boolean"){h=l.styling}else{k(c+"Invalid styling parameter")}}return function(n,r){var s;var y;var q;var m;
var t;var v;var x;var o;var w;var z;var p;var u=false;if(n.event==="newFrame"||n.event==="resizeFrame"){o=n.width;w=n.height;if(typeof(window.innerWidth)=="number"){z=window.innerWidth;p=window.innerHeight
}else{if(document.documentElement&&(document.documentElement.clientWidth||document.documentElement.clientHeight)){z=document.documentElement.clientWidth;p=document.documentElement.clientHeight}else{if(document.body&&(document.body.clientWidth||document.body.clientHeight)){z=document.body.clientWidth;
p=document.body.clientHeight}else{z=999;p=999}}}z=Math.max(z,100);p=Math.max(p,100);o=Math.min(o,z);if(w>p){w=p;u=true}}if(n.closeFrame&&a){e(c+"Received event with closeFrame=true, closing frame");s=document.getElementById(d);
if(s){s.innerHTML=""}else{e(c+"Warning: Container element not found")}}if(n.event==="newFrame"){e(c+"Got request for new frame to url "+n.url);if(n.hidden){b=document.createElement("iframe");b.className=j+"_iframeHidden";
b.setAttribute("src",n.url);b.style.display="none";b.style.width="0px";b.style.height="0px";a=document.createElement("div");a.className=j;a.appendChild(b)}else{b=document.createElement("iframe");b.className=j+"_iframe";
b.setAttribute("src",n.url);b.setAttribute("frameBorder","0");b.style.width=o+"px";b.style.height=w+"px";y=document.createElement("div");y.className=j+"_iframeContainer";y.appendChild(b);x=document.createTextNode(g);
v=document.createElement("span");v.appendChild(x);t=document.createElement("a");t.setAttribute("href","#");t.className=j+"_closeLink";t.onclick=function(){r.sendCloseEvent();return false};t.appendChild(v);
q=document.createElement("div");q.className=j+"_closeContainer";q.appendChild(t);m=document.createElement("div");m.className=j+"_frame4";m.appendChild(q);m.appendChild(y);s=document.createElement("div");
s.className=j+"_frame3";s.appendChild(m);m=s;s=document.createElement("div");s.className=j+"_frame2";s.appendChild(m);m=s;s=document.createElement("div");s.className=j+"_frame1";s.appendChild(m);m=s;i=document.createElement("div");
i.className=j+"_centerFrame";i.style.position="absolute";i.style.top="50%";i.style.left="50%";i.style.width=""+o+"px";i.style.height=""+w+"px";i.style.marginLeft="-"+(o/2)+"px";i.style.marginTop="-"+(w/2)+"px";
i.appendChild(m);m=i;s=document.createElement("div");s.className=j+"_fullPage";s.style.position="fixed";s.style.top="0px";s.style.bottom="0px";s.style.left="0px";s.style.right="0px";s.onclick=function(){if(b&&b.contentWindow){b.contentWindow.focus()
}return false};s.appendChild(m);m=s;a=document.createElement("div");a.className=j;a.appendChild(m);s=document.createElement("div");s.className=j+"_extra1";a.appendChild(s);s=document.createElement("div");
s.className=j+"_extra2";a.appendChild(s)}s=document.getElementById(d);if(s){s.innerHTML="";s.appendChild(a);f=new Date().getTime()}else{e(c+"Container element not found")}}else{if(n.event==="resizeFrame"){b.style.width=o+"px";
b.style.height=w+"px";i.style.width=""+o+"px";i.style.height=""+w+"px";i.style.marginLeft="-"+(o/2)+"px";i.style.marginTop="-"+(w/2)+"px";f=new Date().getTime()}}}}}"use strict";if(window.location.hash.indexOf("#msg:")===0){if(!window.postMessage){(function(){var a=window.parent.parent;
if(a&&a!==window&&a!==window.parent){try{var b=window.location.hash.substring(5);b=decodeURIComponent(b);window.NOKIA.sso.Logging.log("NoA SDK: Received callback URL message, sending to local: "+b);a.NOKIA.sso.Communication.sendMessageToLocal(b)
}catch(c){window.NOKIA.sso.Logging.log("NoA SDK: Failed to decode callback URL message")}}})()}};